apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::635066407893:role/spot-eks-node-group-20240118192431408500000003
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::635066407893:role/general-eks-node-group-20240118192431454900000005
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-01-18T19:44:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2210"
  uid: 7ddec34d-4162-4194-8e62-6cd07847649b
