apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZWNJdUhFb0orVjR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1qSXhORE01TkRKYUZ3MHpOREF4TVRreE5EUTBOREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURXckNwMm1idlRORUZvMytyTjlEaVRGSnFKY3hOOS9RNGNBaEIrOWJ6MTZ5a3l5WWlqRU5POTJTUHIKbEJRT0Z1eXpMZVJlZ2wxQ3piYnhaaEZQZWZHRVByL1E4NTIvSWxtS1gxMDBidGg1WUozemdOR09vcUllQ0RzKwp5cm05alpZSVFHRm1TNUg1UlJQVXZQZEtvL1ppWW5wS1I5aXN4K05pVHEzREV4bmJTRUppWHVaUXU3dittUjNwCll6YXl6dkgvVnlMbW83WU1YWTR0OUdnYVlVZ2o0VXM0ZXNJVWxseThPbE1HMmFtakNLNVVjaHdIV3I1ajQ0SlMKL2l5ZXQzS1Z6RjRXNU5WN2Fhd1dMMTRXRzJ2d05hdjJTbzBXUlozWXpLMzhwNENwYlVKaEQxd09TVUNqdmQrNwpIM1EzSVRzbFY3RU1BdnZtR1hlT1dVUk4xY3VOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQXBKeVlLdFVzNFh6RHNjS1ZuWUx3T3JBSndEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkVPSnpEZVVaeApibGd3dWJxemR2a0xaaEVaRzhucWxmTFgvQkF2d2RyWWZUOExkYU5IeTB2c1JYWncyOUpnV3AyWXJZQXZIazZKCnRmQ0NWVEUzQmVOK0xnK05nNmFSZFcrcWdaZnY2WVZMVVZwL0VKdFEwelp5YzdqSCtIZi9iNytjN2gySTBrUC8KRXBqRG9RbWVaTmxHTVRGQ3h3WHpTbGRhRXhiYi9URUs1RnU3cnRyVXM2aHZjeHRiM0JHczhtZXhNdEpJV1AyOAp0a1EyUkVrUVJHb1JwNzZlMnlwbEpvdFJISnlubTBRTjFYY0c4V2xnaFBIemoraW5DSGVBOXIxb3F2bndQZGpvCjYxSUszckY1b2UyVmxYby9FTkUvVDkxRmdEWE9URG1pOUtDNEwxWXpmQ1gyY3pXZVJUK01tcXpWT0VGbWo4WjMKNkpFb0VWcGYvOFY1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://BEDF5DC939EAE0DB1D3F0727F1152ECD.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
    user: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
  name: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
current-context: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:635066407893:cluster/my-eks2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-eks2
      - --output
      - json
      - --role
      - arn:aws:iam::635066407893:role/tf-master
      command: aws
      env:
      - name: AWS_PROFILE
        value: default
