---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: {{ .Values.az1 }}
spec:
  securityGroups:
    - {{ .Values.securitygroup}}
  subnet: {{ .Values.subnet1 }}

---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: {{ .Values.az2 }}
spec:
  securityGroups:
    - {{ .Values.securitygroup}}
  subnet: {{ .Values.subnet2 }}